export enum ErrorCode {
  // General
  INTERNAL_ERROR = "INTERNAL_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  RATE_LIMITED = "RATE_LIMITED",

  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  EMAIL_EXISTS = "EMAIL_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  ACCOUNT_DISABLED = "ACCOUNT_DISABLED",
  AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_EMAIL_EXISTS = "AUTH_EMAIL_EXISTS",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",

  // Product
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",

  // Order
  CART_EMPTY = "CART_EMPTY",
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  ORDER_CANNOT_CANCEL = "ORDER_CANNOT_CANCEL",
  ORDER_INVALID_STATUS = "ORDER_INVALID_STATUS",
  INVALID_PAYMENT = "INVALID_PAYMENT",

  // Review
  REVIEW_EXISTS = "REVIEW_EXISTS",
  REVIEW_ALREADY_EXISTS = "REVIEW_ALREADY_EXISTS",
  REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND",

  // File
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  FILE_INVALID_TYPE = "FILE_INVALID_TYPE",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
}
